import { Company } from "@/shared/types/CompanyType";

export const initialCompanies: Company[] = [
  {
    company_id: "1",
    company_name: "Green Bites",
    phone_number: "+1 555-100-2000",
    email: "hello@greenbites.com",
    logo_url:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=64&h=64&fit=crop&auto=format",
    business_type: "RESTAURANT",
    user_need_to_know: "Vegan-friendly menu",
    rating: 4.35,
    location_latitude: 40.7128,
    location_longitude: -74.006,
    working_hours: "Mon-Sun 09:00-22:00",
    telegram_link: null,
    social_profile_link: "https://instagram.com/greenbites",
    password_hash: null,
    token_mb: null,
    token_frb: null,
    status: "ACTIVE",
    notification_enabled: 1,
    about: "Organic, sustainable, locally sourced.",
    updated_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    deleted: 0,
  },
  {
    company_id: "2",
    company_name: "Sunrise Bakery",
    phone_number: "+44 20 7999 1000",
    email: "contact@sunrisebakery.co.uk",
    logo_url:
      "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=64&h=64&fit=crop&auto=format",
    business_type: "BAKERY",
    user_need_to_know: "Freshly baked daily",
    rating: 4.8,
    location_latitude: 51.5074,
    location_longitude: -0.1278,
    working_hours: "Mon-Fri 07:00-18:00",
    telegram_link: null,
    social_profile_link: null,
    password_hash: null,
    token_mb: null,
    token_frb: null,
    status: "INACTIVE",
    notification_enabled: 0,
    about: "Gluten-free options.",
    updated_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
    deleted: 0,
  },
  {
    company_id: "3",
    company_name: "City Cafe",
    phone_number: "+998 90 111 22 33",
    email: "info@citycafe.uz",
    logo_url:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=64&h=64&fit=crop&auto=format",
    business_type: "CAFE",
    user_need_to_know: "Fast Wi-Fi, great coffee",
    rating: 3.9,
    location_latitude: 41.2995,
    location_longitude: 69.2401,
    working_hours: "Mon-Sun 08:00-23:00",
    telegram_link: "https://t.me/citycafe",
    social_profile_link: null,
    password_hash: null,
    token_mb: null,
    token_frb: null,
    status: "BANNED",
    notification_enabled: 1,
    about: "Cozy place for meetings.",
    updated_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000 * 90).toISOString(),
    deleted: 1,
  },
];
